# pytest.ini

[pytest]
# Point pytest to your tests directory
testpaths = app/tests

# Ensure Python treats /app as the root package
pythonpath = /app

# Optional: make output cleaner
addopts = -ra -q
